### PR TITLE
Add support for macOS

### PR DESCRIPTION
**Pull request by ospfranco**
needed support for react-native-macos, since the code is simple and has no platform specific dependencies simply adding it seems to make it work... but only with the debugger connected (which makes me think it will only work on a production build, which I cannot test right now) seems related to: https://github.com/uuidjs/uuid/issues/416

### CODE REVIEW

**Comment by LinusU** [comment]
Hmmm, if it only works with the debugger connected I think it is because it's falling back to `Math.random`, which means that it will not work on a production build. This probably needs some more investigation...

**Comment by ospfranco** [comment]
Hey, sorry, I completely forgot about this and I'm just taking a look one more time, you are absolutely right, the fact that only works with the debugger attached is not good.

However I'm not really a macOS/iOS developer, but do you have any idea what could be going wrong, some pointer would be useful to start taking a loook

**Comment by ospfranco** [comment]
I just remerged master changes into my fork and everything seems to be running fine :)

**Comment by ospfranco** [comment]
Turns out I did a small mistake, when importing the package it was not my first import but I imported it after my react-native modules, by moving in on top of my index.js file everything is working fine! so this PR can me merged

**Comment by ospfranco** [comment]
Hello? can we merge this PR?

**Comment by ospfranco** [comment]
@LinusU

**Comment by ospfranco** [comment]
Pinging one more time for this PR to be merged

**Comment by LinusU** [comment]
sorry for the delay

**Comment by LinusU** [comment]
Released as [🚢 1.6.0 / 2021-02-16](https://github.com/LinusU/react-native-get-random-values/releases/tag/v1.6.0)

**Comment by millsmcilroy** [comment]
This closes issue #10

**Pull request merged**
